server:
  port: 8080

spring:
  application:
    name: credcard-transaction-service
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/credcarddb?stringtype=unspecified
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      generate-ddl: false
    properties:
      hibernate:
        batch_versioned_data: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  sql:
    init:
      mode: always